{{- if and .Values.admin.enabled .Values.admin.password (not .Values.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reststop-navigator.fullname" . }}-admin
  labels:
    {{- include "reststop-navigator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.admin.secretKey }}: {{ .Values.admin.password | quote }}
{{- end }}
